# Generated by Django 4.2.3 on 2023-11-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=75)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['task', 'date'],
            },
        ),
    ]
