# Generated by Django 4.2.3 on 2023-11-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completion_status',
            field=models.BooleanField(default=False),
        ),
    ]
