# Generated by Django 4.2.3 on 2023-11-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApi', '0002_todo_completion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
